# Generated by Django 3.0.3 on 2020-02-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Disabled')], default=1),
        ),
        migrations.AlterField(
            model_name='story',
            name='type',
            field=models.IntegerField(choices=[('1', 'Image'), ('2', 'Album'), ('3', 'Video'), ('4', 'Text')], default='1'),
        ),
    ]
