# Generated by Django 3.0.3 on 2020-02-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_auto_20200218_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='type',
            field=models.IntegerField(choices=[(1, 'Image'), (2, 'Album'), (3, 'Video'), (4, 'Text')], default=1),
        ),
    ]
