# Generated by Django 3.0.3 on 2020-02-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_auto_20200218_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='logbook.Topic'),
        ),
        migrations.AlterField(
            model_name='story',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='logbook.User'),
        ),
    ]
